version: '3.3'

services:

    postgres:
        image: 'postgres:17'
        container_name: moviepilot-postgres
        environment:
            POSTGRES_DB: moviepilot
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - '/root/postgresql:/var/lib/postgresql/data'
        ports:
            - target: 5432
              published: 5432
              protocol: tcp
        restart: always

    moviepilot-server:
        image: 'jxxghp/moviepilot-server:latest'
        container_name: moviepilot-server
        environment:
            - DATABASE_TYPE=postgresql
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_NAME=moviepilot
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - CONFIG_DIR=/config
        ports:
            - target: 3001
              published: 3001
              protocol: tcp
        volumes:
            - '/root/moviepilot:/config'
        depends_on:
            - postgres
        restart: always

    cookiecloud:
        image: 'easychen/cookiecloud:latest'
        container_name: cookiecloud
        environment:
            - 'API_ROOT=/cookiecloud'
        ports:
            - target: 8088
              published: 8088
              protocol: tcp
        volumes:
            - '/mnt/cookiecloud:/data/api/data'
        restart: always

    etherpad:
        image: 'etherpad/etherpad:latest'
        container_name: etherpad
        ports:
            - target: 9001
              published: 9009
              protocol: tcp
        volumes:
            - '/root/etherpad:/opt/etherpad-lite/var'
        environment:
            - 'ADMIN_PASSWORD='
        restart: always

    ocr:
        image: 'jxxghp/moviepilot-ocr:latest'
        container_name: ocr
        ports:
            - target: 9899
              published: 9899
              protocol: tcp
        restart: always

    wiki:
        image: 'ghcr.io/requarks/wiki:2.5'
        container_name: wiki
        environment:
            DB_TYPE: sqlite
            DB_FILEPATH: /config/wiki.db
        volumes:
            - '/root/wiki:/config'
        ports:
            - target: 3000
              published: 3000
              protocol: tcp
        restart: unless-stopped

    moviepilot-miniapp:
        image: 'jxxghp/moviepilot-miniapp:latest'
        container_name: moviepilot-miniapp
        environment:
            - TELEGRAM_BOT_TOKEN='8497254084:AAHx6GqIOSMDSntYKDhwXJx8XFO4Tnamw_o'
            - WEBAPP_URL='https://movie-pilot.org/miniapp/'
            - API_BASE_URL='https://movie-pilot.org'
        volumes:
            - '/app/config:/config'
        ports:
            - target: 80
              published: 8000
              protocol: tcp
        restart: always
